version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-supplychain
    environment:
      POSTGRES_DB: supplychain_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-supplychain
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@supplychain.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 